---
- name: Set up emulation tools
  hosts: deck
  gather_facts: no

  tasks:
    - name: Install RetroDECK
      flatpak:
        name: net.retrodeck.retrodeck
        method: user
        state: present
        remote: flathub

    - name: Download (but not run or install) the EmuDeck installer
      get_url:
        url: https://www.emudeck.com/EmuDeck.desktop
        dest: /home/deck/Desktop/EmuDeck.desktop
