---
- name: Set up emulation tools
  hosts: deck

  tasks:
    - name: Set up flatpak
      shell: |
        flatpak --user \
                remote-add \
                --if-not-exists \
                flathub https://flathub.org/repo/flathub.flatpakrepo
      
    - name: Install RetroDeck
      flatpak:
        name: net.retrodeck.retrodeck
        method: user
        state: present
        remote: flathub
