---
- name: System setup
  hosts: deck
  become: yes
  gather_facts: no

  tasks:
    # SSH 
    - name: Upload SSH keys
      authorized_key:
        user: deck
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

    - name: Disable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present

    - name: Disable password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present

    - name: Enable X11 forwarding
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^X11Forwarding'
        line: "X11Forwarding yes"
        state: present

    - name: Enable SSH
      systemd:
        name: sshd
        enabled: yes
        state: restarted
        daemon_reload: yes

    # System apps that DO NOT survive SteamOS updates
    - name: Disable Read-only
      shell: steamos-readonly disable

    - name: Install some tools using pacman
      pacman:
        name:
          - podman
          - fuse-overlayfs
          - slirp4netns
          - wireshark-qt
        state: latest

    # There is a better of doing this but this just werks for now
    - name: Set uid/gid for rootless containers
      shell: |
        touch /etc/subuid /etc/subgid
        chmod 644 /etc/subuid /etc/subgid
        usermod --add-subuids 100000-165535 --add-subgids 100000-165535 deck

    - name: Install distrobox
      shell: curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh

    - name: deck user
      user:
        name: deck
        groups: wheel,wireshark
        append: yes


    

